name: hello-world
on: push
jobs:
  hello-world-job:
    name: Random action
    runs-on: ubuntu-latest
    steps:
      - name: Check original working directory
        shell: bash
        run: |
          echo "$(pwd)"
      - name: Create some random file
        shell: bash
        run: |
          echo "random text." > randomtext.txt
          echo "$(ls -lA)"
      - name: Check out repository code
        uses: actions/checkout@v4
        run: |
          echo "$(pwd)"

#    - name: Copy randomtext.txt into some location in repo
#      shell: bash
#      run: 

# name: hello-world
# on: push
# jobs:
#     upload-sample-file:
#         runs-on: ubuntu-latest
#         steps:
#             - name: Checkout repository
#               uses: actions/checkout@v4
#             - name: Install Python
#               uses: actions/setup-python@v5
#               with:
#                 python-version: '3.13'
#             - name: Install dependencies
#               run: pip install -r requirements.txt
#             - name: Run script
#               working-directory: ./src
#               run: python create_file.py
#             - name: Upload sample file
#               uses: actions/upload-artifact@v4
#               with:
#                 name: sample-file
#                 #working-directory: ./src
#                 path: src/sample_file.txt
#                 #path: ./output_files/sample_file.txt
